---
- stat: path=/usr/bin/phantomjs
  register: phantomjs_stat
  tags:
     - phantomjs

- shell: phantomjs -v
  register: phantomjs_version
  when: phantomjs_stat.stat.exists == True
  tags:
     - phantomjs

- name: Installing phantomjs
  get_url: url=https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-2.1.1-linux-x86_64.tar.bz2 dest=/usr/local/share
  when: phantomjs_stat.stat.exists == False or phantomjs_version != '2.1.1'
  tags:
     - phantomjs

- name: Unarchive phantomjs
  shell: tar xjf /usr/local/share/phantomjs-2.1.1-linux-x86_64.tar.bz2 -C /usr/local/share
  when: phantomjs_stat.stat.exists == False or phantomjs_version != '2.1.1'
  tags:
     - phantomjs

- name: Creating bin links
  shell: ln -sf /usr/local/share/phantomjs-2.1.1-linux-x86_64/bin/phantomjs /usr/local/share/phantomjs
  when: phantomjs_stat.stat.exists == False or phantomjs_version != '2.1.1'
  tags:
     - phantomjs

- shell: ln -sf /usr/local/share/phantomjs-2.1.1-linux-x86_64/bin/phantomjs /usr/local/bin/phantomjs
  when: phantomjs_stat.stat.exists == False or phantomjs_version != '2.1.1'
  tags:
     - phantomjs

- shell: ln -sf /usr/local/share/phantomjs-2.1.1-linux-x86_64/bin/phantomjs /usr/bin/phantomjs
  when: phantomjs_stat.stat.exists == False or phantomjs_version != '2.1.1'
  tags:
     - phantomjs
